# Словарь локализации для AI Study Assistant
# Поддерживает RU, EN, UZ

TRANSLATIONS = {
    "ru": {
        "welcome": "👋 Добро пожаловать в AI Study Assistant!\n\nЭто ваша интеллектуальная система обучения для медвузов.",
        "select_lang": "🌍 Выберите язык интерфейса:",
        "lang_changed": "✅ Язык изменен на Русский!",
        "reg_fio": "✍️ Введите ваше ФИО (Полностью):",
        "reg_course": "🔢 Выберите ваш текущий курс:",
        "reg_year": "📅 Введите год поступления (например: 2023):",
        "reg_faculty": "🎓 Выберите ваш факультет:",
        "reg_success": "🎉 Регистрация успешна!\nПрофиль настроен.",
        "course_saved": "✅ Выбран курс:",
        "course_word": "Курс",
        "menu_theory": "📖 Теория",
        "menu_quiz": "🧠 Тест (AI)",
        "menu_control_test": "📝 Контрольный тест",
        "menu_library": "📚 Библиотека",
        "menu_preparations": "🧫 Препараты",
        "menu_file": "📁 Загрузить тест",
        "menu_sub": "💎 Подписка",
        "menu_info": "ℹ️ Инструкция",
        "menu_profile": "👤 Профиль",
        "menu_stats": "📊 Статистика",
        "menu_admin": "🛠 Админ панель",
        "back": "🔙 В меню",
        "stats_title": "📊 Статистика Бота:",
        "users_total": "👥 Всего пользователей:",
        "stats_langs": "🌍 По языкам:",
        "stats_courses": "🎓 По курсам:",
        "change_profile": "⚙️ Изменить профиль",
        "change_lang": "🌍 Сменить язык",
        "edit_profile_menu": "✏️ Что хотите изменить?",
        "edit_fio": "👤 ФИО",
        "edit_course": "📚 Курс",
        "edit_year": "📅 Год поступления",
        "edit_faculty": "🎓 Факультет",
        "edit_saved": "✅ Сохранено!",
        "err_num": "❌ Введите число.",
        "err_min_20": "⚠️ Минимум 20 вопросов.",
        "err_empty_file": "❌ Ошибка. Файл пуст или имеет неверный формат.",
        "err_gen": "❌ Не удалось сгенерировать вопросы. Попробуйте снова.",
        "limit_reached": "🚫 Вы исчерпали 3 бесплатных запроса.\n\n💎 Купите Premium за 10 000 UZS и получите безлимитный доступ!",
        "requests_left": "💡 Осталось бесплатных запросов: {n}",
        "premium_active": "✅ У вас активен Premium!\nБезлимитный доступ ко всем функциям.",
        "premium_title": "💎 AI Study Assistant Premium",
        "premium_desc": "Безлимитный доступ ко всем функциям.\nЦена: 10 000 UZS / месяц.",
        "buy_premium_btn": "💳 Оплатить 10 000 UZS",
        "payment_success": "🎉 Оплата прошла! Premium активирован.\nТеперь у вас безлимитный доступ. Удачной учёбы!",
        "payment_instructions": "💳 Для оплаты переведите ровно {amount} UZS на карту:\n\n<code>{card}</code>\n\n⚠️ Переводите ТОЧНУЮ сумму — это ваш уникальный идентификатор платежа.\n\nПосле оплаты нажмите кнопку ниже.",
        "check_payment_btn": "✅ Я оплатил(а)",
        "payment_pending": "⏳ Платёж ещё не поступил. Подождите 1-2 минуты и попробуйте снова.",
        "payment_error": "❌ Ошибка проверки платежа. Попробуйте позже.",
        "payment_cancelled": "❌ Платёж отменён.",
        "no_pending": "❌ Активный платёж не найден. Нажмите «Купить Premium» заново.",
        "multi_ans_hint": "ℹ️ Здесь {n} правильных ответа. Выберите ровно {n} варианта.",
        "select_limit_hint": "Можно выбрать только допустимое количество вариантов.",
        "submit_answer": "✅ Ответить",
        "correct": "✅ Верно!",
        "wrong": "❌ Неверно.",
        "finished": "🏁 Тест завершен!",
        "result": "📈 Ваш результат:",
        "grade_label": "Оценка:",
        "grade_excellent": "5 (Отлично)",
        "grade_good": "4 (Хорошо)",
        "grade_satisfactory": "3 (Удовлетворительно)",
        "grade_fail": "2 (Неудовлетворительно)",
        "results_file_prefix": "Результаты_теста",
        "theory_file_prefix": "Теория",
        "answer_file_prefix": "Ответ",
        "download_caption": "📥 Ваш файл с тестами и объяснениями от ИИ.",
        "theory_pdf_caption": "📖 Ваш структурированный учебный материал (PDF).",
        "answer_pdf_caption": "📖 Ваш ответ (PDF).",
        "drawing_start": "🎨 Рисую чертеж... Это займет пару секунд.",
        "drawing_fail": "❌ Ошибка при создании чертежа. Уточните запрос.",
        "search_books": "🔍 Профессор ищет информацию по книгам...",
        "write_lecture": "✍️ Пишу конспект и перевожу материал...",
        "off_topic": "🚫 Этот вопрос не относится к медицине или гистологии.\n\nПожалуйста, задайте вопрос по теме: гистология, анатомия, физиология, биохимия или другие медицинские дисциплины.",
        "check_books": "📚 ИИ проверяет наличие книг и карту знаний...",
        "lib_empty": "📭 Библиотека пока пуста",
        "select_section": "🏛 Выберите раздел:",
        "prep_empty": "📭 Раздел препаратов пока пуст.",
        "prep_select_category": "🧫 Выберите категорию препаратов:",
        "prep_select_item": "📂 Выберите препарат:",
        "prep_not_found": "❌ Файл препарата не найден",
        "or_new_topic": "Или введите новую тему:",
        "repeat_topic": "🔄 Повторно изучить:",
        "ktp_btn": "📅 По КТП",
        "custom_btn": "✍️ Своя тема",
        "ktp_select": "📅 Выберите тему из КТП:",
        "ktp_lectures": "Лекции",
        "ktp_practicals": "Практические",
        "ktp_no_data": "❌ КТП для вашего факультета не найден.",
        "enter_topic": "✍️ Введите тему для конспекта:",
        "enter_quiz_topic": "✍️ Введите тему для теста:",
        "select_quiz_type": "📝 Тип теста:",
        "quiz_type_closed": "📋 Yopiq test (с вариантами)",
        "quiz_type_open": "✏️ Ochiq test (без вариантов)",
        "enter_quiz_count": "🔢 Сколько вопросов сгенерировать? (напишите число):",
        "gen_wait": "⏳ Генерирую вопросы, подождите...",
        "quiz_ready": "✅ Тест готов! Начинаем.",
        "control_test_not_available": "ℹ️ Сейчас нет активного контрольного теста.",
        "control_test_choose": "📝 Выберите контрольный тест из списка:",
        "control_test_unavailable_pick": "ℹ️ Этот тест больше недоступен. Выберите другой.",
        "control_test_starting": "📝 Запускаю контрольный тест: {title}",
        "open_choose_from_options": "📌 Ниже варианты. Напишите один правильный вариант (или его букву).",
        "open_type_hint": "✏️ Напишите ваш ответ текстом:",
        "checking_answer": "🧠 Проверяю ответ...",
        "open_correct": "✅ Верно!",
        "open_wrong": "❌ Неверно.",
        "open_correct_was": "📖 Правильный ответ:",
        "quiz_starting": "вопросов загружено. Начинаем...",
        "ai_analyzing": "🧠 ИИ анализирует ваш файл и пишет объяснения...",
        "clean_file_wait": "⏳ Читаю ваш файл...",
        # Факультеты
        "fac_lech": "Лечебное дело",
        "fac_ped": "Педиатрия",
        "fac_stom": "Стоматология",
        "fac_medped": "Мед. педагогика",
        "fac_medprof": "Мед. профилактика",
        "fac_farm": "Фармация",
        "fac_nurse": "ВМСО (Медсестры)",
        "fac_mil": "Воен. медицина",
        "fac_inter": "Международный",
        "fac_postgrad": "Ординатура/Магистратура",
        # Обратная связь
        "feedback_btn": "📩 Обратная связь",
        "fb_request": "Помог ли вам этот материал? Оставьте отзыв!",
        "fb_ask": "Выберите тип обращения:",
        "fb_review": "🌟 Оставить отзыв",
        "fb_bug": "🐞 Сообщить об ошибке",
        "fb_feature": "💡 Предложить функцию",
        "fb_prompt": "📝 Напишите ваше сообщение (одним текстом):",
        "fb_success": "✅ Спасибо! Ваше сообщение успешно отправлено разработчикам."
    },
    "en": {
        "welcome": "👋 Welcome to AI Study Assistant!\n\nThis is your intelligent learning system for medical universities.",
        "select_lang": "🌍 Select interface language:",
        "lang_changed": "✅ Language changed to English!",
        "reg_fio": "✍️ Enter your Full Name:",
        "reg_course": "🔢 Select your current course/year:",
        "reg_year": "📅 Enter your admission year (e.g. 2023):",
        "reg_faculty": "🎓 Select your faculty:",
        "reg_success": "🎉 Registration successful!\nProfile configured.",
        "course_saved": "✅ Course selected:",
        "course_word": "Course",
        "menu_theory": "📖 Theory",
        "menu_quiz": "🧠 Quiz (AI)",
        "menu_control_test": "📝 Control Test",
        "menu_library": "📚 Library",
        "menu_preparations": "🧫 Preparations",
        "menu_file": "📁 Upload Test",
        "menu_sub": "💎 Subscription",
        "menu_info": "ℹ️ Info",
        "menu_profile": "👤 Profile",
        "menu_stats": "📊 Statistics",
        "menu_admin": "🛠 Admin Panel",
        "back": "🔙 Main Menu",
        "stats_title": "📊 Bot Statistics:",
        "users_total": "👥 Total users:",
        "stats_langs": "🌍 By language:",
        "stats_courses": "🎓 By course:",
        "change_profile": "⚙️ Edit Profile",
        "change_lang": "🌍 Change Language",
        "edit_profile_menu": "✏️ What would you like to change?",
        "edit_fio": "👤 Full Name",
        "edit_course": "📚 Course",
        "edit_year": "📅 Admission Year",
        "edit_faculty": "🎓 Faculty",
        "edit_saved": "✅ Saved!",
        "err_num": "❌ Enter a number.",
        "err_min_20": "⚠️ Minimum 20 questions.",
        "err_empty_file": "❌ Error. File is empty or has an invalid format.",
        "err_gen": "❌ Failed to generate questions. Please try again.",
        "limit_reached": "🚫 You have used all 3 free requests.\n\n💎 Buy Premium for 10,000 UZS and get unlimited access!",
        "requests_left": "💡 Free requests remaining: {n}",
        "premium_active": "✅ You have Premium! Unlimited access.",
        "premium_title": "💎 AI Study Assistant Premium",
        "premium_desc": "Unlimited access to all features.\nPrice: 10,000 UZS / month.",
        "buy_premium_btn": "💳 Pay 10,000 UZS",
        "payment_success": "🎉 Payment successful! Premium activated.\nYou now have unlimited access. Good luck studying!",
        "payment_instructions": "💳 Transfer exactly {amount} UZS to the card:\n\n<code>{card}</code>\n\n⚠️ Transfer the EXACT amount — this is your unique payment identifier.\n\nAfter paying, press the button below.",
        "check_payment_btn": "✅ I've paid",
        "payment_pending": "⏳ Payment not received yet. Wait 1-2 minutes and try again.",
        "payment_error": "❌ Payment check error. Please try later.",
        "payment_cancelled": "❌ Payment cancelled.",
        "no_pending": "❌ No active payment found. Press 'Buy Premium' again.",
        "multi_ans_hint": "ℹ️ There are {n} correct answers. Select exactly {n} options.",
        "select_limit_hint": "You can only select the allowed number of options.",
        "submit_answer": "✅ Submit",
        "correct": "✅ Correct!",
        "wrong": "❌ Wrong.",
        "finished": "🏁 Quiz finished!",
        "result": "📈 Your result:",
        "grade_label": "Grade:",
        "grade_excellent": "5 (Excellent)",
        "grade_good": "4 (Good)",
        "grade_satisfactory": "3 (Satisfactory)",
        "grade_fail": "2 (Fail)",
        "results_file_prefix": "Quiz_Results",
        "theory_file_prefix": "Theory",
        "answer_file_prefix": "Answer",
        "download_caption": "📥 Your test file with AI explanations.",
        "theory_pdf_caption": "📖 Your structured study material (PDF).",
        "answer_pdf_caption": "📖 Your answer (PDF).",
        "drawing_start": "🎨 Drawing diagram... This will take a few seconds.",
        "drawing_fail": "❌ Error creating diagram. Please refine your query.",
        "search_books": "🔍 Professor is searching through medical literature...",
        "write_lecture": "✍️ Writing lecture and translating material...",
        "off_topic": "🚫 This question is not related to medicine or histology.\n\nPlease ask a question about histology, anatomy, physiology, biochemistry, or other medical subjects.",
        "check_books": "📚 AI is checking books and knowledge map...",
        "lib_empty": "📭 Library is empty",
        "select_section": "🏛 Select a section:",
        "prep_empty": "📭 Preparations section is empty.",
        "prep_select_category": "🧫 Choose a preparation category:",
        "prep_select_item": "📂 Choose a preparation file:",
        "prep_not_found": "❌ Preparation file not found",
        "or_new_topic": "Or enter a new topic:",
        "repeat_topic": "🔄 Study again:",
        "ktp_btn": "📅 By schedule",
        "custom_btn": "✍️ Custom topic",
        "ktp_select": "📅 Select topic from schedule:",
        "ktp_lectures": "Lectures",
        "ktp_practicals": "Practicals",
        "ktp_no_data": "❌ Schedule not found for your faculty.",
        "enter_topic": "✍️ Enter topic for the lecture:",
        "enter_quiz_topic": "✍️ Enter topic for the quiz:",
        "select_quiz_type": "📝 Test type:",
        "quiz_type_closed": "📋 Yopiq test (with options)",
        "quiz_type_open": "✏️ Ochiq test (no options)",
        "enter_quiz_count": "🔢 How many questions to generate? (enter a number):",
        "gen_wait": "⏳ Generating questions, please wait...",
        "quiz_ready": "✅ Quiz is ready! Let's start.",
        "control_test_not_available": "ℹ️ No active control test is available right now.",
        "control_test_choose": "📝 Choose a control test from the list:",
        "control_test_unavailable_pick": "ℹ️ This test is no longer available. Please choose another one.",
        "control_test_starting": "📝 Starting control test: {title}",
        "open_choose_from_options": "📌 Options are below. Type one correct option (or its letter).",
        "open_type_hint": "✏️ Write your answer:",
        "checking_answer": "🧠 Checking answer...",
        "open_correct": "✅ Correct!",
        "open_wrong": "❌ Incorrect.",
        "open_correct_was": "📖 Correct answer:",
        "quiz_starting": "questions loaded. Starting...",
        "ai_analyzing": "🧠 AI is analyzing your file and writing explanations...",
        "clean_file_wait": "⏳ Reading your file...",
        # Faculties
        "fac_lech": "General Medicine",
        "fac_ped": "Pediatrics",
        "fac_stom": "Dentistry",
        "fac_medped": "Medical Pedagogy",
        "fac_medprof": "Medical Prevention",
        "fac_farm": "Pharmacy",
        "fac_nurse": "Higher Nursing",
        "fac_mil": "Military Medicine",
        "fac_inter": "International",
        "fac_postgrad": "Residency/Masters",
        # Feedback
        "feedback_btn": "📩 Feedback",
        "fb_request": "Did this material help you? Leave feedback!",
        "fb_ask": "Select feedback type:",
        "fb_review": "🌟 Leave a review",
        "fb_bug": "🐞 Report a bug",
        "fb_feature": "💡 Suggest a feature",
        "fb_prompt": "📝 Write your message (in one text):",
        "fb_success": "✅ Thank you! Your message has been sent to the developers."
    },
    "uz": {
        "welcome": "👋 AI Study Assistant ga xush kelibsiz!\n\nBu tibbiyot OTMlari uchun intellektual o'qitish tizimi.",
        "select_lang": "🌍 Interfeys tilini tanlang:",
        "lang_changed": "✅ Til O'zbek tiliga o'zgartirildi!",
        "reg_fio": "✍️ F.I.Sh ni kiriting (To'liq):",
        "reg_course": "🔢 Hozirgi kursingizni tanlang:",
        "reg_year": "📅 O'qishga kirgan yilingizni kiriting (masalan: 2023):",
        "reg_faculty": "🎓 Fakultetingizni tanlang:",
        "reg_success": "🎉 Ro'yxatdan o'tish muvaffaqiyatli!\nProfil sozlandi.",
        "course_saved": "✅ Kurs tanlandi:",
        "course_word": "Kurs",
        "menu_theory": "📖 Nazariya",
        "menu_quiz": "🧠 Test (AI)",
        "menu_control_test": "📝 Nazorat testi",
        "menu_library": "📚 Kutubxona",
        "menu_preparations": "🧫 Preparatlar",
        "menu_file": "📁 Test yuklash",
        "menu_sub": "💎 Obuna",
        "menu_info": "ℹ️ Yo'riqnoma",
        "menu_profile": "👤 Profil",
        "menu_stats": "📊 Statistika",
        "menu_admin": "🛠 Admin panel",
        "back": "🔙 Bosh menyu",
        "stats_title": "📊 Bot Statistikasi:",
        "users_total": "👥 Jami foydalanuvchilar:",
        "stats_langs": "🌍 Tillar bo'yicha:",
        "stats_courses": "🎓 Kurslar bo'yicha:",
        "change_profile": "⚙️ Profilni O'zgartirish",
        "change_lang": "🌍 Tilni o'zgartirish",
        "edit_profile_menu": "✏️ Nimani o'zgartirmoqchisiz?",
        "edit_fio": "👤 F.I.Sh",
        "edit_course": "📚 Kurs",
        "edit_year": "📅 O'qishga kirgan yil",
        "edit_faculty": "🎓 Fakultet",
        "edit_saved": "✅ Saqlandi!",
        "err_num": "❌ Son kiriting.",
        "err_min_20": "⚠️ Kamida 20 ta savol.",
        "err_empty_file": "❌ Xato. Fayl bo'sh yoki noto'g'ri formatda.",
        "err_gen": "❌ Savollar yaratib bo'lmadi. Qaytadan urinib ko'ring.",
        "limit_reached": "🚫 3 ta bepul so'rovingiz tugadi.\n\n💎 10 000 UZS ga Premium xarid qiling va cheksiz foydalaning!",
        "requests_left": "💡 Qolgan bepul so'rovlar: {n}",
        "premium_active": "✅ Sizda Premium faol! Cheksiz kirish.",
        "premium_title": "💎 AI Study Assistant Premium",
        "premium_desc": "Barcha funksiyalarga cheksiz kirish.\nNarxi: 10 000 UZS / oy.",
        "buy_premium_btn": "💳 10 000 UZS to'lash",
        "payment_success": "🎉 To'lov muvaffaqiyatli! Premium faollashtirildi.\nEndi cheksiz kirishingiz bor. O'qishda omad!",
        "payment_instructions": "💳 Aynan {amount} UZS ni quyidagi kartaga o'tkazing:\n\n<code>{card}</code>\n\n⚠️ AYNAN shu summani o'tkaring — bu sizning to'lovingizning noyob identifikatori.\n\nTo'lovdan so'ng quyidagi tugmani bosing.",
        "check_payment_btn": "✅ To'ladim",
        "payment_pending": "⏳ To'lov hali kelmadi. 1-2 daqiqa kuting va qayta urinib ko'ring.",
        "payment_error": "❌ To'lovni tekshirishda xatolik. Keyinroq urinib ko'ring.",
        "payment_cancelled": "❌ To'lov bekor qilindi.",
        "no_pending": "❌ Faol to'lov topilmadi. 'Premium xarid qilish' tugmasini qayta bosing.",
        "multi_ans_hint": "ℹ️ Bu savolda {n} ta to'g'ri javob bor. Aynan {n} ta variantni tanlang.",
        "select_limit_hint": "Faqat ruxsat etilgan miqdordagi variantni tanlash mumkin.",
        "submit_answer": "✅ Javob berish",
        "correct": "✅ To'g'ri!",
        "wrong": "❌ Xato.",
        "finished": "🏁 Test yakunlandi!",
        "result": "📈 Natijangiz:",
        "grade_label": "Baho:",
        "grade_excellent": "5 (A'lo)",
        "grade_good": "4 (Yaxshi)",
        "grade_satisfactory": "3 (Qoniqarli)",
        "grade_fail": "2 (Qoniqarsiz)",
        "results_file_prefix": "Test_natijalari",
        "theory_file_prefix": "Nazariya",
        "answer_file_prefix": "Javob",
        "download_caption": "📥 AI tushuntirishlari bilan test faylingiz.",
        "theory_pdf_caption": "📖 Sizning tartiblangan o'quv materialingiz (PDF).",
        "answer_pdf_caption": "📖 Sizning javobingiz (PDF).",
        "drawing_start": "🎨 Chizma tayyorlanmoqda... Bir necha soniya vaqt oladi.",
        "drawing_fail": "❌ Chizma yaratishda xatolik. Boshqa atama kiriting.",
        "search_books": "🔍 Professor kitoblardan ma'lumot qidirmoqda...",
        "write_lecture": "✍️ Ma'ruza yozyapman va tarjima qilyapman...",
        "off_topic": "🚫 Bu savol tibbiyot yoki gistologiyaga aloqador emas.\n\nIltimos, gistologiya, anatomiya, fiziologiya, biokimyo yoki boshqa tibbiy fanlar bo'yicha savol bering.",
        "check_books": "📚 AI kitoblarni va bilimlar xaritasini tekshirmoqda...",
        "lib_empty": "📭 Kutubxona bo'sh",
        "select_section": "🏛 Bo'limni tanlang:",
        "prep_empty": "📭 Preparatlar bo'limi hozircha bo'sh.",
        "prep_select_category": "🧫 Preparatlar kategoriyasini tanlang:",
        "prep_select_item": "📂 Preparat faylini tanlang:",
        "prep_not_found": "❌ Preparat fayli topilmadi",
        "or_new_topic": "Yoki yangi mavzu kiriting:",
        "repeat_topic": "🔄 Qayta o'rganish:",
        "ktp_btn": "📅 Jadval bo'yicha",
        "custom_btn": "✍️ O'z mavzuim",
        "ktp_select": "📅 Jadvaldan mavzu tanlang:",
        "ktp_lectures": "Ma'ruzalar",
        "ktp_practicals": "Amaliy darslar",
        "ktp_no_data": "❌ Sizning fakultetingiz uchun jadval topilmadi.",
        "enter_topic": "✍️ Ma'ruza mavzusini kiriting:",
        "enter_quiz_topic": "✍️ Test mavzusini kiriting:",
        "select_quiz_type": "📝 Test turini tanlang:",
        "quiz_type_closed": "📋 Yopiq test (javob variantlari bilan)",
        "quiz_type_open": "✏️ Ochiq test (javob variantlarsiz)",
        "enter_quiz_count": "🔢 Nechta savol yaratish kerak? (son kiriting):",
        "gen_wait": "⏳ Savollar yaratilmoqda, kuting...",
        "quiz_ready": "✅ Test tayyor! Boshladik.",
        "control_test_not_available": "ℹ️ Hozircha faol nazorat testi yo'q.",
        "control_test_choose": "📝 Ro'yxatdan nazorat testini tanlang:",
        "control_test_unavailable_pick": "ℹ️ Bu test endi mavjud emas. Boshqasini tanlang.",
        "control_test_starting": "📝 Nazorat testi boshlandi: {title}",
        "open_choose_from_options": "📌 Variantlar quyida. Bitta to'g'ri variantni (yoki harfini) yozing.",
        "open_type_hint": "✏️ Javobingizni matn shaklida yozing:",
        "checking_answer": "🧠 Javob tekshirilmoqda...",
        "open_correct": "✅ To'g'ri!",
        "open_wrong": "❌ Noto'g'ri.",
        "open_correct_was": "📖 To'g'ri javob:",
        "quiz_starting": "savol yuklandi. Boshladik...",
        "ai_analyzing": "🧠 AI faylingizni tahlil qilib, tushuntirishlar yozmoqda...",
        "clean_file_wait": "⏳ Faylingizni o'qiyapman...",
        # Факультеты
        "fac_lech": "Davolash ishi",
        "fac_ped": "Pediatriya",
        "fac_stom": "Stomatologiya",
        "fac_medped": "Tibbiy pedagogika",
        "fac_medprof": "Tibbiy profilaktika",
        "fac_farm": "Farmatsiya",
        "fac_nurse": "OMH (Hamshiralik)",
        "fac_mil": "Harbiy tibbiyot",
        "fac_inter": "Xalqaro fakultet",
        "fac_postgrad": "Ordinatura/Magistratura",
        # Обратная связь
        "feedback_btn": "📩 Fikr bildirish",
        "fb_request": "Ushbu material yordam berdimi? Fikr bildiring!",
        "fb_ask": "Murojaat turini tanlang:",
        "fb_review": "🌟 Fikr qoldirish",
        "fb_bug": "🐞 Xatoni xabar qilish",
        "fb_feature": "💡 Yangilik taklif qilish",
        "fb_prompt": "📝 Xabaringizni yozing (bitta matnda):",
        "fb_success": "✅ Rahmat! Xabaringiz dasturchilarga yuborildi."
    }
}

def t(key, lang="ru"):
    return TRANSLATIONS.get(lang, TRANSLATIONS["ru"]).get(key, key)
